version: "3.9"
services:

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    image: translators/backend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./apps/backend:/app

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    image: translators/frontend
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./apps/frontend:/app
